print("#######################")
print("#                     #")
print("# Muhammad Ibnu Sina  #")
print("#    2410817210024    #")
print("#                     #")
print("#######################")