Nama = input ("Nama                 : ")
NIM = input ("NIM                  : ")
Kelas = input ("Kelas Paralel        : ")
ttl = input ("Tempat/Tanggal Lahir : ")
Alamat = input ("Alamat               : ")
Hobby = input ("Hobby                : ")
HP = input ("No.HP                : ")

print(f"\nNama                : {Nama}")
print(f"NIM                  : {NIM}")
print(f"Kelas Paralel        : {Kelas}")
print(f"Tempat/Tanggal Lahir : {ttl}")
print(f"Alamat               : {Alamat}")
print(f"Hobby                : {Hobby}")
print(f"No.HP                : {HP}")